language: php

cache:
    directories:
        - $HOME/.composer/cache/files

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - nightly
  - hhvm

before_install:
  - composer self-update

install:
  - composer install
